### ISSUE TITLE
Exception thrown at line 160: System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by tmxkn1** [edoreshef/magnet-winforms#1]
Hi there, thanks for your excellent work!

The issue mentioned here can be reproduced with the following steps:
1. Stick a child form to the main form.
2. Drag the main form to the top edge of your screen, so the form gets enlarged automatically.
3. Drag the main form off the top edge, so the form shank to its original size.
Then you will get the exception suggested by the title.

**Comment by edoreshef** [comment]
Thanks for the feedback.
Bug was fixed.
